# Generated by Django 5.0.3 on 2024-04-06 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank='Название категории', default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank='Название блюда', default='', max_length=100)),
                ('desc', models.CharField(blank='Описание', default='', max_length=100)),
                ('steps', models.CharField(blank='Шаги приготовления', default='', max_length=100)),
                ('time', models.DecimalField(blank='Время приготовления', decimal_places=0, max_digits=5)),
                ('pic', models.ImageField(blank='Изображение', upload_to='')),
                ('tm', models.TextField(blank='Автор', default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank='Название категории', on_delete=django.db.models.deletion.CASCADE, to='recapp.category')),
                ('recs', models.ForeignKey(blank='Рецепты', on_delete=django.db.models.deletion.CASCADE, to='recapp.recipe')),
            ],
        ),
    ]
