# Generated by Django 5.0.3 on 2024-04-06 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Название категории', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', help_text='Название блюда', max_length=100)),
                ('desc', models.CharField(default='', help_text='Описание', max_length=100)),
                ('steps', models.CharField(default='', help_text='Шаги приготовления', max_length=100)),
                ('time', models.DecimalField(decimal_places=0, help_text='Время приготовления (n часов)', max_digits=5)),
                ('pic', models.ImageField(help_text='Изображение', upload_to='')),
                ('tm', models.TextField(default='', help_text='Автор', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(help_text='Название категории', on_delete=django.db.models.deletion.CASCADE, to='recapp.category')),
                ('recs', models.ForeignKey(help_text='Рецепты', on_delete=django.db.models.deletion.CASCADE, to='recapp.recipe')),
            ],
        ),
    ]
