# Generated by Django 5.0.3 on 2024-04-06 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reccat',
            name='category',
            field=models.ForeignKey(default='', help_text='Название категории', on_delete=django.db.models.deletion.SET_DEFAULT, to='recapp.category'),
        ),
        migrations.AlterField(
            model_name='reccat',
            name='recs',
            field=models.ForeignKey(default='', help_text='Рецепты', on_delete=django.db.models.deletion.SET_DEFAULT, to='recapp.recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Время приготовления (n часов)', max_digits=5),
        ),
    ]
